In [1]:
print("Waqas Ahmad Batch 8 PIAIC139128")


Waqas Ahmad Batch 8 PIAIC139128


In [2]:
import numpy as NPWaqas

In [3]:
#method/attribute 1
NPWaqas.array([10,12,13,14,15,16,17,18,19,20])

array([10, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
#method/attribut 2 arange
arr = NPWaqas.arange(3*5).reshape(3, 5)
 

In [5]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
#method/attribute 3
arr.ndim




2

In [10]:
#method/attribute 4
arr.dtype.name


'int32'

In [12]:
#method/attribute 5
arr.size



15

In [11]:
#method/attribute 6
arr.itemsize

In [15]:
#method/attribute 7
type(arr)

numpy.ndarray

In [16]:
#method/attribute 8
larr=NPWaqas.zeros((5, 6))    
larr


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
#method/attribute 9
larr2=NPWaqas.ones( (2,3,4), dtype=NPWaqas.int32 )   
larr2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [31]:
#method/attribute 10
emptyarr=NPWaqas.empty( (2,3) ) 
emptyarr

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [23]:
#method/attribute 11 reshape

arr3 =NPWaqas.arange(10000).reshape(100,100)
arr3

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [25]:
#method/attribute 12 
rg = NPWaqas.random.default_rng(1)
rg

Generator(PCG64) at 0x29E2F892E50

In [26]:
#method/attribute 13 
b = rg.random((2,3))
b
    

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [27]:
#method/attribute 14
cexp= NPWaqas.arange(3)
NPWaqas.exp(cexp)
cexp

array([0, 1, 2])

In [28]:
#method/attribute 15
NPWaqas.sqrt(cexp)


array([0.        , 1.        , 1.41421356])

In [30]:
#method/attribute 16
D= NPWaqas.array([2., -1., 4.])
NPWaqas.add(D, cexp)

array([2., 0., 6.])

In [33]:
#method/attribute 17
NPWaqas.shape(emptyarr)

(2, 3)

In [34]:
#method/attribute 18
a4 = NPWaqas.floor(10*rg.random((3,4)))
a4

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [35]:
#method/attribute 19
a4.ravel()

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [36]:
#method/attribute 20
a4.T

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [42]:
#method/attribute 21

a4.min() 

0.0

In [43]:
#method/attribute 22
a4.max() 

8.0

In [44]:
#method/attribute 23
a4.sum()


51.0

In [45]:
#method/attribute 25
a4.mean()

4.25

In [47]:
#method/attribute 26
NPWaqas.random.seed(0)

In [48]:
#method/attribute 27

NPWaqas.abs(a4)
a4

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [49]:
#method/attribute 28
NPWaqas.power(a4,3)

array([[512.,  64., 125.,   0.],
       [343., 125.,  27., 343.],
       [ 27.,  64.,   1.,  64.]])

In [50]:
#method/attribute 29
NPWaqas.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
#method/attribute 30
NPWaqas.pi

3.141592653589793

In [52]:
#method/attribute 31
NPWaqas.cos(a4)

array([[-0.14550003, -0.65364362,  0.28366219,  1.        ],
       [ 0.75390225,  0.28366219, -0.9899925 ,  0.75390225],
       [-0.9899925 , -0.65364362,  0.54030231, -0.65364362]])

In [53]:
#method/attribute 32
NPWaqas.sin(a4)

array([[ 0.98935825, -0.7568025 , -0.95892427,  0.        ],
       [ 0.6569866 , -0.95892427,  0.14112001,  0.6569866 ],
       [ 0.14112001, -0.7568025 ,  0.84147098, -0.7568025 ]])

In [54]:
#method/attribute 33
diag = NPWaqas.diag([4,5,7])
diag

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [55]:
#method/attribute 34
a4.cumsum()

array([ 8., 12., 17., 17., 24., 29., 32., 39., 42., 46., 47., 51.])

In [56]:
#method/attribute 35
a4.cumprod()


array([  8.,  32., 160.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.])

In [57]:
#method/attribute 36
a4.any()

True

In [58]:
#method/attribute 37
a4.all()

False

In [59]:
#method/attribute 38
a4.sort()
a4

array([[0., 4., 5., 8.],
       [3., 5., 7., 7.],
       [1., 3., 4., 4.]])

In [60]:
#method/attribute 39
NPWaqas.tan(a4)

array([[ 0.        ,  1.15782128, -3.38051501, -6.79971146],
       [-0.14254654, -3.38051501,  0.87144798,  0.87144798],
       [ 1.55740772, -0.14254654,  1.15782128,  1.15782128]])

In [64]:
#method/attribute 40
NPWaqas.log(larr2)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
#method/attribute 41
NPWaqas.log10(larr2)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [66]:
#method/attribute 42
NPWaqas.log2(larr2)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
#method/attribute 43
NPWaqas.add.reduce(larr2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [68]:
#method/attribute 44
NPWaqas.multiply.reduce(larr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [71]:
#method/attribute 45
NPWaqas.unique(a4)

array([0., 1., 3., 4., 5., 7., 8.])

In [73]:
#method/attribute 46
a4.transpose()

array([[0., 3., 1.],
       [4., 5., 3.],
       [5., 7., 4.],
       [8., 7., 4.]])

In [74]:
#method/attribute 47
a4.trace()

9.0

In [78]:
#method/attribute 48
arr8=NPWaqas.random.randint(4,10,(3,3))
arr8


array([[6, 8, 4],
       [4, 8, 6],
       [5, 4, 5]])

In [79]:
#method/attribute 49
NPWaqas.hsplit(arr8,3)

[array([[6],
        [4],
        [5]]),
 array([[8],
        [8],
        [4]]),
 array([[4],
        [6],
        [5]])]

In [80]:
#method/attribute 50
arr8.argmin()

2

In [81]:
#method/attribute 51
arr8.argmax()

1

In [82]:
#method/attribute 52
NPWaqas.lcm(5, 11)

55

In [83]:
#method/attribute 53
NPWaqas.prod([15,3])

45

In [84]:
#method/attribute 54
NPWaqas.gcd(19,3)

1

In [85]:
#method/attribute 55
NPWaqas.random.normal(size = (4,4))

array([[ 0.48431215,  0.57914048, -0.18158257,  1.41020463],
       [-0.37447169,  0.27519832, -0.96075461,  0.37692697],
       [ 0.03343893,  0.68056724, -1.56349669, -0.56669762],
       [-0.24214951,  1.51439128, -0.3330574 ,  0.04736482]])

In [86]:
#method/attribute 56
NPWaqas.random.uniform(size =(4,4))

array([[0.6176355 , 0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787, 0.21038256],
       [0.1289263 , 0.31542835, 0.36371077, 0.57019677]])

In [87]:
#method/attribute 57
NPWaqas.random.gamma(5)

5.224406533530308